version = 1

[[annotations]]
path = [
 "assets/**",
 "config/**",
 "lib/**",
 "mix.exs",
 "mix.lock",
 "priv/**",
 "rootfs_overlay/**",
 "REUSE.toml",
 "test/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "assets/vendor/topbar.js"
]
precedence = "override"
SPDX-FileCopyrightText = "2021 Buu Nguyen"
SPDX-License-Identifier = "MIT"
