version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".formatter.exs",
 ".github/**",
 ".gitignore",
 ".tool-versions",
 "assets/**",
 "CHANGELOG.md",
 "config/**",
 "lib/**",
 "mix.exs",
 "mix.lock",
 "README.md",
 "priv/**",
 "rel/**",
 "rootfs_overlay/**",
 "REUSE.toml",
 "test/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "assets/vendor/topbar.js"
]
precedence = "override"
SPDX-FileCopyrightText = "2021 Buu Nguyen"
SPDX-License-Identifier = "MIT"
